# Generated by Django 5.1.1 on 2024-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='creditHours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='eligibilityCriteria',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
